'use client';

import { useEffect, useRef, useState } from 'react';
import ResumeChat from './ResumeChat';
import SystemExplorer from './SystemExplorer';
import BlockLighting from './BlockLighting';
import { ArrowDown, ArrowUpRight, Check, Code2, Copy, Database, Github, Layers, Mail, MapPin, Menu, Moon, Smartphone, Sun, Terminal, Users, X } from 'lucide-react';

const projects = [
  { id: '01', title: 'IT equipment maintenance and reporting.', name: 'PM Management', category: 'Web', year: '2026', type: 'Full-stack application', tags: ['React', 'TypeScript', 'Node.js', 'SQL Server', 'Docker'], description: 'An IT equipment maintenance platform with role-based access, configurable checklists, and a clear audit trail.', details: ['Built the full stack with React, TypeScript, Node.js, Express, Prisma, and SQL Server.', 'Implemented JWT authentication, role-based access, configurable PM checklists, and activity logging.', 'Created Excel reports with ExcelJS and cost-summary visualizations with Recharts.', 'Containerized the application stack with Docker Compose.'], icon: Database },
  { id: '02', title: 'Mobile application and companion website.', name: 'Mobile Application', category: 'Mobile', year: '2025', type: 'KCE Electronics PCL', tags: ['Mobile development', 'UX/UI', 'Database design'], description: 'End-to-end mobile development, paired with a website for data visualization.', details: ['Designed the database and UX/UI for every screen of the mobile application and accompanying website.', 'Developed image uploads, search, data sorting, and personalized screens for each user.', 'Created a companion website for data visualization.'], icon: Smartphone },
  { id: '03', title: 'Maintenance and feature development.', name: 'Web Application Enhancement', category: 'Web', year: '2025', type: 'KCE Electronics PCL', tags: ['Web development', 'Excel export', 'Data sorting'], description: 'Reviewed an inherited codebase and delivered improvements shaped by client requirements.', details: ['Inherited and reviewed an existing application from a previous developer.', 'Added Excel file export, data sorting, and additional data columns.', 'Enhanced the web application to match client requirements.'], icon: Code2 },
  { id: '04', title: 'Inventory, skills, and in-game economy.', name: 'Turn-Based Strategy Game', category: 'Game', year: '2023–2024', type: 'Game development project', tags: ['Inventory', 'Skill systems', 'Game UI'], description: 'Connected inventory, upgradable skills, and an in-game economy in a turn-based strategy game.', details: ['Designed and developed a character inventory system.', 'Built an upgradable skill system with usage conditions.', 'Created a shop for purchasing and upgrading weapons and integrated it with the in-game currency.', 'Designed a user-friendly, visually appealing game interface.'], icon: Layers },
];
const softSkills = ['Self learning', 'Quick learner', 'Attention to detail', 'Team collaboration', 'Adaptability'];
const coreStack = ['TypeScript', 'JavaScript', 'Node.js', 'C#', '.NET', 'SQL', 'Flutter', 'HTML', 'CSS', 'Docker'];
const skills = [
  { title: 'Frontend & mobile', icon: Code2, items: ['React', 'TypeScript', 'JavaScript', 'HTML', 'CSS', 'Dart + Flutter', 'Vite'] },
  { title: 'Backend & data', icon: Database, items: ['Node.js', 'Express', 'Prisma', 'SQL', 'SQL Server', 'MySQL', 'PHP', 'Laravel', '.NET', 'Python', 'C', 'C#', 'Java'] },
  { title: 'Soft skills', icon: Users, items: softSkills },
  { title: 'Tools & workflow', icon: Terminal, items: ['Docker', 'Git', 'VS Code', 'Visual Studio', 'Android Studio', 'Unity', 'SSMS', 'Canva', 'Microsoft Office', 'Antigravity', 'Windsurf'] },
];
export default function Home() {
  const [activeSection, setActiveSection] = useState('');
  useEffect(() => {
    const observer = new IntersectionObserver(entries => { for (const entry of entries) if (entry.isIntersecting) setActiveSection(entry.target.id); }, { rootMargin: '-20% 0px -50% 0px' });
    document.querySelectorAll('main section[id]').forEach(section => observer.observe(section));
    return () => observer.disconnect();
  }, []);
  const [filter, setFilter] = useState('All');
  const [selected, setSelected] = useState<(typeof projects)[number] | null>(null);
  const [light, setLight] = useState(false);
  const [menu, setMenu] = useState(false);
  const [copied, setCopied] = useState(false);
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { try { setLight(localStorage.getItem('portfolio-theme') === 'light'); } catch {} }, []);
  useEffect(() => { document.documentElement.dataset.theme = light ? 'light' : 'dark'; }, [light]);
  useEffect(() => { if (selected) { dialog.current?.showModal(); const original = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = original; }; } }, [selected]);
  function closeProject() { dialog.current?.close(); setSelected(null); }
  function toggleTheme() { setLight(!light); try { localStorage.setItem('portfolio-theme', !light ? 'light' : 'dark'); } catch {} }
  async function copyEmail() { try { await navigator.clipboard.writeText('Suteemon_Yodying@hotmail.com'); setCopied(true); setTimeout(() => setCopied(false), 2500); } catch { window.location.href = 'mailto:Suteemon_Yodying@hotmail.com'; } }
  return <>
    <ResumeChat/>
    <BlockLighting/>
    <a className="skip" href="#main">Skip to content</a>
    <header className="header"><a href="#" className="logo" aria-label="Suteemon home">SY<span>.</span></a>
      <nav aria-label="Main navigation" className={menu ? 'nav open' : 'nav'}>{['Work', 'About', 'Skills', 'Contact'].map(item => <a key={item} href={'#' + item.toLowerCase()} aria-current={activeSection === item.toLowerCase() ? 'location' : undefined} onClick={() => setMenu(false)}>{item}</a>)}</nav>
      <div className="header-actions"><button className="icon-button" onClick={toggleTheme} aria-label={light ? 'Switch to dark theme' : 'Switch to light theme'}>{light ? <Moon size={19}/> : <Sun size={19}/>}</button><a className="github-link" href="https://github.com/XXRTH-S" target="_blank" rel="noreferrer"><Github size={18}/> GitHub <ArrowUpRight size={15}/></a><button className="icon-button mobile-menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></div>
    </header>
    <main id="main">
      <section className="hero wrap">
        <div className="hero-copy"><div className="eyebrow"><span className="little-line"/> FULL-STACK DEVELOPMENT / AI EXPLORATION</div><p className="intro">Hello, I’m Suteemon.</p><h1>Fullstack<br/><span>developer</span></h1><p className="hero-description">I build and maintain web and mobile applications, from databases to user interfaces. Currently a Full-Stack Developer at Bangkok Expressway and Metro.</p><div className="hero-buttons"><a className="button primary" href="#work">Explore my work <ArrowDown size={18}/></a><a className="button secondary" href="#contact">Get in touch <Mail size={18}/></a></div><div className="location"><MapPin size={15}/> Bangkok, Thailand <span> / </span> Web · Mobile · Full-stack</div></div>
        <SystemExplorer/>
      </section>
      <div className="stack-bar"><div className="wrap"><span>MY CORE STACK</span>{coreStack.map(s => <strong key={s}>{s}</strong>)}</div></div>
      <section id="work" className="section wrap"><div className="section-heading"><div><div className="eyebrow">01 / SELECTED WORK</div><h2>Selected projects<span>.</span></h2></div><p>Selected development work, with implementation details and technologies used.</p></div><div className="filters" aria-label="Filter projects">{['All', 'Web', 'Mobile', 'Game'].map(f => <button key={f} aria-pressed={f === filter} onClick={() => setFilter(f)}>{f}{f === 'All' && <span>04</span>}</button>)}</div><div className="project-grid" aria-live="polite">{projects.filter(p => filter === 'All' || p.category === filter).map(p => <button className={'project-card project-' + p.id} key={p.id} onClick={() => setSelected(p)} aria-haspopup="dialog"><div className="project-top"><span>{p.category.toUpperCase()} / {p.year}</span><ArrowUpRight size={22}/></div><div className="project-visual"><p.icon size={38} strokeWidth={1.25}/><span>{p.id}</span></div><div className="project-content"><span className="project-type">{p.type}</span><h3>{p.name}</h3><p>{p.description}</p><div className="tags">{p.tags.map(t => <span key={t}>{t}</span>)}</div><div className="project-bottom">Explore project <ArrowUpRight size={17}/></div></div></button>)}</div></section>
      <section id="about" className="section about-section"><div className="wrap about-grid"><div><div className="eyebrow">02 / A LITTLE ABOUT ME</div><h2>Professional background<span>.</span></h2><p className="about-copy">I’m Suteemon Yodying, a full-stack developer with hands-on experience delivering complete web and mobile applications, from database design to user interface.</p><p className="muted">I currently work as a Full-Stack Developer at Bangkok Expressway and Metro Public Company Limited, covering frontend, backend, databases, and system integration. My experience includes React and Node.js web platforms, SQL Server, and cross-platform mobile applications with Flutter. I focus on maintainable solutions and continuously expanding my technical knowledge.</p><div className="soft-skills">{softSkills.map(s => <span key={s}><Check size={15}/>{s}</span>)}</div><div className="languages"><span>Thai <b>Native</b></span><span>English <b>Good</b></span></div></div><div className="journey"><h3>Work experience</h3><article><span className="timeline-date">Present</span><h4>Bangkok Expressway and Metro Public Company Limited</h4><p>Full-Stack Developer</p><ul className="muted"><li>Develop and maintain web applications across frontend, backend, databases, and system integration.</li><li>Enhance existing systems and codebases based on business requirements and user needs.</li><li>Troubleshoot issues and continuously improve functionality, usability, and performance.</li></ul></article><article><span className="timeline-date">2025</span><h4>KCE Electronics PCL</h4><p>Full-Stack Developer</p><span className="muted">End-to-end mobile development and improvements to an existing web application.</span></article><h3 className="timeline-group-heading">Education</h3><article><span className="timeline-date">2020 — 2024</span><h4>Silpakorn University</h4><p>Computer Science</p><span className="muted">Education</span></article><h3 className="timeline-group-heading">Project timeline</h3><article><span className="timeline-date">2026</span><h4>PM Management Web Application</h4><p>Full-stack project</p><span className="muted">Role-based workflows, reporting, and Docker deployment for IT equipment maintenance.</span></article><article><span className="timeline-date">2023–2024</span><h4>Turn-Based Strategy Game</h4><p>Game development project</p><span className="muted">Inventory, skill upgrades, and in-game economy systems.</span></article></div></div></section>
      <section id="skills" className="section wrap"><div className="section-heading"><div><div className="eyebrow">03 / MY TOOLKIT</div><h2>Technical skills & workflow<span>.</span></h2></div><p>Technologies used across web, mobile, backend, and development workflows.</p></div><div className="skills-grid">{skills.map(s => <article className="skill-card" key={s.title}><s.icon size={25}/><h3>{s.title}</h3><div className="tags">{s.items.map(i => <span key={i}>{i}</span>)}</div></article>)}</div></section>
      <section id="contact" className="contact wrap"><div className="eyebrow">04 / GET IN TOUCH</div><h2>Let’s discuss<br/><span>your project or role.</span></h2><a className="contact-email" href="mailto:Suteemon_Yodying@hotmail.com">Suteemon_Yodying@hotmail.com <ArrowUpRight/></a><div className="contact-actions"><a className="button primary" href="mailto:Suteemon_Yodying@hotmail.com"><Mail size={18}/> Say hello</a><button className="button secondary" onClick={copyEmail}>{copied ? <Check size={17}/> : <Copy size={17}/>}<span role="status">{copied ? 'Email copied' : 'Copy email'}</span></button><a className="phone" href="tel:+66841015526">+66 84 101 5526</a></div></section>
    </main><footer className="wrap"><span>© {new Date().getFullYear()} Suteemon Yodying</span><span>Built with Next.js & React</span><a href="#">Back to top ↑</a></footer>
    <dialog ref={dialog} onCancel={closeProject} onClick={e => { if (e.target === e.currentTarget) closeProject(); }} aria-labelledby="project-title"><div className="dialog-body"><button className="icon-button close-dialog" onClick={closeProject} aria-label="Close project"><X/></button>{selected && <><div className="eyebrow">{selected.category} / {selected.year}</div><h2 id="project-title">{selected.name}</h2><p className="dialog-subtitle">{selected.title}</p><p>{selected.description}</p><h3>What I built</h3><ul>{selected.details.map(d => <li key={d}>{d}</li>)}</ul><div className="tags">{selected.tags.map(t => <span key={t}>{t}</span>)}</div><a className="button secondary" href="https://github.com/XXRTH-S" target="_blank" rel="noreferrer"><Github size={18}/> Visit my GitHub profile <ArrowUpRight size={16}/></a></>}</div></dialog>
  </>;
}
